language: minimal
services:
  - docker
script:
  - docker build --no-cache --pull -t quay.io/wisvch/modify-password:$TRAVIS_BUILD_NUMBER .
deploy:
  provider: script
  script: >-
    sh -c '
    docker login -u "$QUAY_USERNAME" -p "$QUAY_PASSWORD" quay.io;
    docker push quay.io/wisvch/modify-password:$TRAVIS_BUILD_NUMBER;
    '
  on:
    branch: master
notifications:
  email: false
  slack:
    rooms:
      secure: CTH8+ryJ1go66OjpqLa4bKgy+DAslaIV7p7AxKwuFPKMUe6lGiIy4Fm55yQbzpcbcETn6BarOylHVWUacH0KXVb7SfTErpRlI1NITzD2zvVe8di9qMP4K/+sWqvzHl6cUQhqJY5iRIBWsLT56+PqeR/0hRbP+1YCcxrBfHXqQc1yjKSba4VM5rP7jbpg5wpoQETU9l1shAURgcWbvMSgFCLso+NlW8JST+FISi+t4ajjuS2asnM6yZxeac2XBEHX+fJvaR7HuceWrJZn+TK9daHwjoHy3UwmAG+UcizQc2jQS+LImD86FyBqJ6x/rLZ0mskOOB/O+4FBI/CZXxRfUXv+6TLJ4PBaDF4LGeJcBOm5bdQzP7tj5fQ9uOyMFyjYKg2NxpfwgoMRSzcmh+XOVoW6puaEInKvqEpCxMUCQi4APaBZ4QxdnczYl3R9XEwbOQeTKDEKSKnGSbo2S3YKYmnhMgjdwpKqsJSfKeGCMTTIYf7kgJJn14fH+IR/n/jbk4k/zYVX3a3MlZWDgq63IE+PF7uECL0FCg3CV0o7fnq7XDBq2H+llaZyRO0A2c7d5anlcQOIfE6zRF6cWD8eXPmRkeqFBbxgCQ9GITZu6/gMYCakhRIvymFbPUXyl/sk7AXbFpfKOU+G/Q771drqwV4GWEJcODLsZqKH45TsR+w=
